# This is a basic workflow to help you get started with Actions

name: CI/CD

env:
  EB_PACKAGE_S3_BUCKET_NAME: 'my-flask-application-packages'
  EB_APPLICATION_NAME: 'Myflaskapp'
  EB_ENVIROMENT_NAME: 'Myflaskapp-env'
  DEPLOY_PACKAGE_NAME: 'flask_app_${{ github.sha }}.zip'
  AWS_REGION_NAME: 'eu-central-1'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies for testing
      run: |
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 --count --statistics --show-source
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --extend-exclude=""
    - name: Test with pytest
      run: | 
        pytest

  deploy:     
    runs-on: ubuntu-latest
    steps:
      - name: Generate deployment package
        run: zip -r {{env.DEPLOY_PACKAGE_NAME }}.zip ./ -x *.git
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: MyApplicationName
          environment_name: MyApplication-Environment
          version_label: 12345
          region: eu-central-1
        
