# This is a basic workflow to help you get started with Actions

name: CI/CD

env:
  EB_PACKAGE_S3_BUCKET_NAME: "my-flask-application-packages"
  EB_APPLICATION_NAME: "Myflaskapp"
  EB_ENVIROMENT_NAME: "Myflaskapp-env"
  DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-central-1"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install dependencies for testing
      run: |
        if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python3 -m pytest

  deploy:     
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@master
        
      - name: Generate deployment package
        run: zip -r {{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.MY_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION_NAME }} 
          
      - name: Copy deployment package to S3 Bucket
        run: aws s3 cp {{ env.DEPLOY_PACKAGE_NAME }} s3:// ${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
          
        
